// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

public partial class AddCourse
{
    protected global::System.Web.UI.WebControls.Content Content1;
    protected global::System.Web.UI.WebControls.Label pageTitle;
    protected global::System.Web.UI.WebControls.TextBox courseCodeTextBox;
    protected global::System.Web.UI.WebControls.TextBox courseNameTextBox;
    protected global::System.Web.UI.WebControls.TextBox descriptionTextBox;
    protected global::System.Web.UI.WebControls.TextBox creditsTextBox;
    protected global::System.Web.UI.WebControls.TextBox semesterTextBox;
    protected global::System.Web.UI.WebControls.DropDownList instructorDropDown;
    protected global::System.Web.UI.WebControls.TextBox maxStudentsTextBox;
    protected global::System.Web.UI.WebControls.Button saveButton;
}
