// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

public partial class AddStudent
{
    protected global::System.Web.UI.WebControls.Content Content1;
    protected global::System.Web.UI.WebControls.Label pageTitle;
    protected global::System.Web.UI.WebControls.TextBox studentNumberTextBox;
    protected global::System.Web.UI.WebControls.TextBox fullNameTextBox;
    protected global::System.Web.UI.WebControls.TextBox emailTextBox;
    protected global::System.Web.UI.WebControls.TextBox dateOfBirthTextBox;
    protected global::System.Web.UI.WebControls.TextBox phoneNumberTextBox;
    protected global::System.Web.UI.WebControls.TextBox cityTextBox;
    protected global::System.Web.UI.WebControls.TextBox addressTextBox;
    protected global::System.Web.UI.WebControls.DropDownList statusDropDown;
    protected global::System.Web.UI.WebControls.Button saveButton;
}
