// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

public partial class Courses
{
    protected global::System.Web.UI.WebControls.Content Content1;
    protected global::System.Web.UI.WebControls.TextBox searchTextBox;
    protected global::System.Web.UI.WebControls.Button searchButton;
    protected global::System.Web.UI.WebControls.Button clearButton;
    protected global::System.Web.UI.WebControls.GridView coursesGridView;
    protected global::System.Web.UI.WebControls.WebControl enrollButton;
    protected global::System.Web.UI.WebControls.WebControl deleteButton;
}
