// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

public partial class Dashboard
{
    protected global::System.Web.UI.WebControls.Content Content1;
    protected global::System.Web.UI.WebControls.Label totalStudentsLabel;
    protected global::System.Web.UI.WebControls.Label totalCoursesLabel;
    protected global::System.Web.UI.WebControls.Label totalEnrollmentsLabel;
    protected global::System.Web.UI.WebControls.Label myCoursesLabel;
    protected global::System.Web.UI.WebControls.GridView recentEnrollmentsGridView;
}
