// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

public partial class MyEnrollments
{
    protected global::System.Web.UI.WebControls.Content Content1;
    protected global::System.Web.UI.WebControls.GridView enrollmentsGridView;
    protected global::System.Web.UI.WebControls.WebControl detailsButton;
    protected global::System.Web.UI.WebControls.WebControl dropButton;
}
