// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

public partial class Register
{
    protected global::System.Web.UI.WebControls.TextBox usernameTextBox;
    protected global::System.Web.UI.WebControls.TextBox fullNameTextBox;
    protected global::System.Web.UI.WebControls.TextBox emailTextBox;
    protected global::System.Web.UI.WebControls.TextBox passwordTextBox;
    protected global::System.Web.UI.WebControls.TextBox confirmPasswordTextBox;
    protected global::System.Web.UI.WebControls.Button registerButton;
}
