// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

public partial class ViewStudent
{
    protected global::System.Web.UI.WebControls.Content Content1;
    protected global::System.Web.UI.WebControls.Label studentNumberLabel;
    protected global::System.Web.UI.WebControls.Label fullNameLabel;
    protected global::System.Web.UI.WebControls.Label emailLabel;
    protected global::System.Web.UI.WebControls.Label dobLabel;
    protected global::System.Web.UI.WebControls.Label phoneLabel;
    protected global::System.Web.UI.WebControls.Label cityLabel;
    protected global::System.Web.UI.WebControls.GridView coursesGridView;
}
